name: Release

on:
  workflow_dispatch: 
  release:
    types: # This configuration does not affect the page_build event above
      - published
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Short SHA and Unique runner id
        id: vars
        run: |
          echo ::set-output name=sha_short::${GITHUB_SHA::7}
          echo ::set-output name=uuid::${{ env.BRANCH_NAME }}:${GITHUB_SHA::7}:${GITHUB_RUN_ID}
      - name: Install Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: create .env file
        run: |
          echo API_CI_SECRET=${{ secrets.API_CI_SECRET }} >> .env
          echo API_CI_TOKEN=${{ secrets.API_CI_TOKEN }} >> .env
          echo API_CI_USER=${{ secrets.API_CI_USER }} >> .env
          echo DEMO_ACCOUNT_SECRET=${{ secrets.DEMO_ACCOUNT_SECRET }} >> .env
          echo DEMO_ACCOUNT_TOKEN=${{ secrets.DEMO_ACCOUNT_TOKEN }} >> .env
          echo DEMO_ACCOUNT_USER=${{ secrets.DEMO_ACCOUNT_USER }} >> .env
      - name: install deps
        run: |
          npm install
      - name: Run integration test
        run: |
          npm run integrationTest
      - name: cleanup
        run: |
          rm .env

  build:
    needs: integration-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org'
        scope: '@ironsource'
    - name: Setup git
      run: |
        git config --global user.name "IronSource"
        git config --global user.email "itayl@is.com"
    - name: Tag version
      run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}
    - name: Install build packages
      run: npm install
    - name: Build package
      run: npm run build
    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      run: |
        npm publish
      shell: bash
